### ISSUE TITLE
incorrect linux gamedata signature for CItem_InventoryBox::RemoveItem

### ISSUE THREAD

**Issue by zeThijs** [dysphie/nmrih-supply-chances-ex#1]
Typo (?) in the key "linux" "@_ZN18CItem_InventoryBox10RemoveItemERKN14ItemCategories10category_eEi", which should be "@_ZN18CItem_InventoryBox10RemoveItemERKN14ItemCategories10category_eEib"

**Comment by dysphie** [comment]
Thank you, Fixed in 1.1.3b
